### ISSUE TITLE
Why only scalaSource ?

### ISSUE THREAD

**Issue by CharlesHD** [Banno/sbt-license-plugin#7]
Gj for your plugin. It's pretty usefull.

Your plugin add header only on scala sources. It may be cool to work with java sources too. In fact, it may be cooler if it could work with any source file.

**Comment by NicolasRouquette** [comment]
Indeed, it would be useful to support scala/javaSources in Compile/Test.

**Comment by adamdecaf** [comment]
I'll get #9 merged and released here soon.

**Comment by adamdecaf** [comment]
@CharlesHD @NicolasRouquette I released version "0.1.3". Does that work for you both?

**Comment by CharlesHD** [comment]
Still not working for me. Got version 0.1.3.
In compile scala sources still get the License but java sources don't.
Maybe i'm doing it wrong.

**Comment by adamdecaf** [comment]
@CharlesHD could you take this branch for a spin? https://github.com/Banno/sbt-license-plugin/compare/license-java-files  I'm not able to figure out how to publish a snapshot to bintray, but If that could happen I can do that for you to test. The version is "0.1.4-SNAPSHOT".

**Comment by CharlesHD** [comment]
Ok. Cloned your work, but don't really know how to deal with unmanaged sbt plugin. What should i do in order to test your snapshot ?

**Comment by adamdecaf** [comment]
@CharlesHD you should be able to just publish-local inside the project. Then bump the version in your project and run "reload" inside sbt for it to resolve the plugin.

**Comment by CharlesHD** [comment]
Thanks, i achieve to make it works. But don't know why java sources still don't get licensed.

**Comment by adamdecaf** [comment]
@CharlesHD that's odd. Is this project open source by chance? The path to the java sources also needs to be under the typical "src/main/java" of a project. Or else we'll need to add that to the source directories for the plugin to check.

**Comment by CharlesHD** [comment]
For testing i made a simple project with a simple java class in src/main/java/ and a simple scala class in src/main/scala/ . After compiling scala one gets licensed but not the java one. Is that working for you ?

**Comment by adamdecaf** [comment]
@CharlesHD odd, that's what the test in https://github.com/Banno/sbt-license-plugin/pull/10 was added for. I'll create a separate project and test it out.

**Comment by CharlesHD** [comment]
Rectification : It works ! I wasn't using the good version. Well thanks a lot for your work on that feature.

**Comment by adamdecaf** [comment]
@CharlesHD awesome! I'll release 0.1.4 then
